# Generated by Django 5.2.7 on 2025-10-08 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capteur',
            name='filtre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.filtre'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='valeur',
            field=models.CharField(max_length=100),
        ),
    ]
