# Generated by Django 5.2.7 on 2025-10-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_capteur_nom_alter_capteur_filtre_alter_capteur_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filtre',
            name='vitesse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtre',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.salle'),
        ),
    ]
