# Generated by Django 5.2.7 on 2025-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_salle_filtre_vitesse_filtre_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtre',
            name='broche_esp32',
            field=models.IntegerField(default=0, help_text="broche GPIO sur l'esp32"),
        ),
    ]
